on:
  workflow_dispatch:

name: Install Test
jobs:
  install:
    name: Simple Install Test
    runs-on: macos-15-large

    steps:
      - name: Install
        run: brew install kopi-vm/tap/kopi

      - name: Setup kopi
        run: kopi setup
      
      - name: Install Java
        run: kopi install 24
      
      - name: Use Java
        run: kopi global 24
      
      - name: Run Java
        run: |
          export PATH="/Users/runner/.kopi/shims:$PATH"
          ls -al /Users/runner/.kopi/jdks/temurin-24.0.2/
          which java
          java --version

  tap-test:
    name: Tap Test
    runs-on: macos-15-large

    steps:
      - name: Tap
        run: brew tap kopi-vm/tap

      - name: Install
        run: brew install kopi

      - name: Setup kopi
        run: kopi setup

