on:
  workflow_dispatch:

name: Install Test
jobs:
  

  install:
    name: Simple Install Test

    strategy:
      matrix:
        os: [ macos-15, macos-15-large ]
        version: [ "24", "zulu@21", "liberica@17" ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install
        run: brew install kopi-vm/tap/kopi

      - name: Setup kopi
        run: kopi setup
      
      - name: Install Java
        run: kopi install ${{ matrix.version }}
      
      - name: Use Java
        run: kopi global ${{ matrix.version }}
      
      - name: Run Java
        run: |
          export PATH="/Users/runner/.kopi/shims:$PATH"
          ls -al /Users/runner/.kopi/jdks/
          kopi env
          kopi current
          java --version

  tap-test:
    name: Tap Test
    strategy:
      matrix:
        os: [ macos-15, macos-15-large ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Tap
        run: brew tap kopi-vm/tap

      - name: Install
        run: brew install kopi

      - name: Setup kopi
        run: kopi setup

